### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by LClingner2**
Please include:
  - Moving store database onto main branch
  - Created schema and seeds
  - @LClingner2 for the fix, @rutger0714 @CharleyDunham @joBrady for review

### CODE REVIEW

**Review by CharleyDunham — CHANGES_REQUESTED** [review]
Looks good, a lot of css changed so they should just affect cosmetics. Need to add the migration file

**Review by joBrady — CHANGES_REQUESTED** [review]
Add the migration file, you made changes to schema but did not add the migration files

**Review by CharleyDunham — APPROVED** [review]
Looks good now, migration file was added.

**Review by joBrady — APPROVED** [review]
Thank you for making the necessary changes

**Pull request merged**
